#!/bin/bash

set -e
set +x

if [ $# -lt 2 ]
  then
    echo "usage: control-linting [--enable  | --disable] target_folder"
fi

COMMAND=$1
FOLDER=$2
PATH_TO_SELF="$(dirname "$0")"

if [ $COMMAND = "--enable" ] 
then
  echo "Enabling linting on all files in $FOLDER" 
  $PATH_TO_SELF/enable-lint-in-files.sh $FOLDER

elif  [ $COMMAND = "--disable" ]; then
  echo "Disabling linting on all files in $FOLDER"  
  $PATH_TO_SELF/disable-lint-in-files.sh $FOLDER
fi



